sonar.projectKey=Hackathon_judge_platform
sonar.projectName=Hackathon Platform
sonar.sourceEncoding=UTF-8
sonar.sources=apps/api/src,apps/web/src,apps/scheduler/src,packages/shared
sonar.exclusions=**/node_modules/**,**/dist/**,**/.next/**,**/.venv/**,**/coverage/**,**/__pycache__/**
